language: node_js

cache:
  directories:
    - "node_modules"

script:
- npm build
- mv docs/* .

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: develop
  target-branch: gh-pages
