language: node_js
node_js:
    - 12

cache:
  directories:
    - "node_modules"

script:
- npm run build
- node generate_grids_list.js grids/
- mv docs/* .

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages

notifications:
  email:
    on_success: never