language: node_js

cache:
  directories:
    - "node_modules"

script:
- npm build
- npm run gen-grids-list
- mv docs/* .

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  target-branch: gh-pages

notifications:
  email:
    on_success: never